--TABLE MARQUE 
CREATE TABLE Marques( 
idMarque INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
nomMarque NVARCHAR(50) NOT NULL,
descMarque NVARCHAR(250) NOT NULL); 

--TABLE OPERATIONS 
CREATE TABLE Operations(
idOp INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
nomOP NVARCHAR(50) NOT NULL, 
dateDebutOp DATETIME2 NOT NULL, 
dateFinOP DATETIME2 NOT NULL,
CONSTRAINT chk_dates CHECK (dateFinOp > dateDebutOp));

--TABLE TAILLE 
CREATE TABLE Tailles(
idTaille INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
nomTaille NVARCHAR(50));

--TABLE COULEUR 
CREATE TABLE Couleurs(
idCouleur INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
nomCouleur NVARCHAR(50)); 

--TABLE CATEGORIES
CREATE TABLE Categories(
idCat INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
nomCat NVARCHAR(50));


--TABLE CLIENTS
CREATE TABLE Clients(
idCli INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
nomCLi NVARCHAR(50) NOT NULL,
prenomCli NVARCHAR(50) NOT NULL, 
emailCli NVARCHAR(50) NOT NULL);

--TABLE PRODUITS 
CREATE TABLE Produits( 
idProd INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
nomProd NVARCHAR(50) NOT NULL, 
descProd NVARCHAR(250) NOT NULL,
idMarque INT NOT NULL,
idCat INT NOT NULL,
CONSTRAINT fk_marqueProd 
	FOREIGN KEY (idMarque)
	REFERENCES Marques(idMarque) 
	ON DELETE CASCADE
	ON UPDATE CASCADE, 
CONSTRAINT fk_catProd 
	FOREIGN KEY (idCat)
	REFERENCES Categories(idCat) 
	ON DELETE CASCADE
	ON UPDATE CASCADE);

--TABLE PROMOTIONs
CREATE TABLE Promotions(
idProd INT NOT NULL,
idOp INT NOT NULL,
idTaille INT NOT NULL,
idCouleur INT NOT NULL,
qteStock INT  NOT NULL, 
pxPromo DECIMAL(10,2) NOT NULL, 
PRIMARY KEY(idProd, idOp, idTaille, idCouleur), 
CONSTRAINT fk_prodProm 
	FOREIGN KEY (idProd)
	REFERENCES Produits(idProd) 
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT fk_opeProm 
	FOREIGN KEY (idOP)
	REFERENCES Operations(idOp) 
	ON DELETE CASCADE
	ON UPDATE CASCADE, 
CONSTRAINT fk_TailleProm 
	FOREIGN KEY (idTaille)
	REFERENCES Tailles(idTaille) 
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT fk_couleurProm 
	FOREIGN KEY (idCouleur)
	REFERENCES Couleurs(idCouleur) 
	ON DELETE CASCADE
	ON UPDATE CASCADE);

--TABLE TARIFS PUBLICS 
CREATE TABLE tarifsPublics( 
idProd INT NOT NULL,
idTaille INT NOT NULL,
idCouleur INT NOT NULL,
pxInit DECIMAL(10,2) NOT NULL,
PRIMARY KEY(idProd, idTaille, idCouleur), 
CONSTRAINT fk_prodTarifPub 
	FOREIGN KEY (idProd)
	REFERENCES Produits(idProd) 
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT fk_TailleTarifPub 
	FOREIGN KEY (idTaille)
	REFERENCES Tailles(idTaille) 
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT fk_couleurTarifPub
	FOREIGN KEY (idCouleur)
	REFERENCES Couleurs(idCouleur) 
	ON DELETE CASCADE
	ON UPDATE CASCADE);

--TABLE COMMENTAIRE 
CREATE TABLE Commentaires(
idComment INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
texte NVARCHAR(250),
note DECIMAL(2,1) NOT NULL, 
CONSTRAINT chk_note CHECK ( note>=0 AND note<=5), 
idProd INT NOT NULL,
CONSTRAINT fk_prodComment
	FOREIGN KEY (idProd)
	REFERENCES Produits(idProd) 
	ON DELETE CASCADE
	ON UPDATE CASCADE,
idCli INT NOT NULL, 
CONSTRAINT fk_cliComment
	FOREIGN KEY (idCli)
	REFERENCES Clients(idCli) 
	ON DELETE CASCADE
	ON UPDATE CASCADE);